import type { Employee } from "./types"

export const employeesSeed: Employee[] = [
  {
    id: "emp-1",
    firstName: "Maya",
    lastName: "Chen",
    email: "maya.chen@sonothing.demo",
    role: "Engineering Director",
    departmentId: "dept-eng",
    avatarUrl: null,
    joinedAt: "2021-03-15",
    status: "active",
    location: "Singapore",
    managerId: null,
  },
  {
    id: "emp-2",
    firstName: "Jordan",
    lastName: "Lee",
    email: "jordan.lee@sonothing.demo",
    role: "Head of Product",
    departmentId: "dept-product",
    avatarUrl: null,
    joinedAt: "2020-11-02",
    status: "active",
    location: "Bangkok",
    managerId: null,
  },
  {
    id: "emp-3",
    firstName: "Sam",
    lastName: "Rivera",
    email: "sam.rivera@sonothing.demo",
    role: "Senior Frontend Engineer",
    departmentId: "dept-eng",
    avatarUrl: null,
    joinedAt: "2022-06-01",
    status: "active",
    location: "Remote",
    managerId: "emp-1",
  },
  {
    id: "emp-4",
    firstName: "Aisha",
    lastName: "Khan",
    email: "aisha.khan@sonothing.demo",
    role: "Product Designer",
    departmentId: "dept-product",
    avatarUrl: null,
    joinedAt: "2023-01-16",
    status: "on_leave",
    location: "Kuala Lumpur",
    managerId: "emp-2",
  },
  {
    id: "emp-5",
    firstName: "Noah",
    lastName: "Patel",
    email: "noah.patel@sonothing.demo",
    role: "People Partner",
    departmentId: "dept-people",
    avatarUrl: null,
    joinedAt: "2019-08-20",
    status: "active",
    location: "Singapore",
    managerId: null,
  },
  {
    id: "emp-6",
    firstName: "Elena",
    lastName: "Voss",
    email: "elena.voss@sonothing.demo",
    role: "Operations Lead",
    departmentId: "dept-ops",
    avatarUrl: null,
    joinedAt: "2021-01-10",
    status: "active",
    location: "Berlin",
    managerId: null,
  },
  {
    id: "emp-7",
    firstName: "Chris",
    lastName: "Okonkwo",
    email: "chris.okonkwo@sonothing.demo",
    role: "Backend Engineer",
    departmentId: "dept-eng",
    avatarUrl: null,
    joinedAt: "2024-04-22",
    status: "active",
    location: "Lagos",
    managerId: "emp-1",
  },
]
